hosts:
  - name: Zues
    host: ssh://zues
  - name: Sidecar
    host: ssh://sidecar
  - name: Frigate
    host: ssh://nvr
  - name: Recipinned
    host: ssh://recipinned
  - name: Gitea Runner
    host: ssh://gitea
