[tools]
# -------------------------------------------------------
# Environments

node = "25"
bun = "latest"
rust = "latest"

# -------------------------------------------------------
# npm

"npm:prettier" = "latest"
"npm:eslint" = "latest"
"npm:typescript" = "latest"
"npm:ts-node" = "latest"
"npm:pnpm" = "latest"
"npm:yarn" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"

# -------------------------------------------------------
# Go

# Go Team Tools
"go:golang.org/x/perf/cmd/benchstat" = "latest"
"go:golang.org/x/tools/cmd/deadcode" = "latest"
"github:amir20/dtop" = "v0.5.0"

# Go Tools
"go:github.com/abice/go-enum" = "latest"
"go:github.com/Zxilly/go-size-analyzer/cmd/gsa" = "latest"
"go:github.com/homeport/dyff/cmd/dyff" = "v1"
"go:github.com/caarlos0/svu/v3" = "latest"

# Grafana Tools
"github:grafana/mcp-grafana" = "v0.7.9"

# Personal Go Tools
"go:github.com/hay-kot/mmdot" = "v0.3.0"
"go:github.com/hay-kot/mdparse" = "v0.1.0"
"github:hay-kot/gofind" = "v0.4.1"
"github:hay-kot/scaffold" = "v0.11.0"

# -------------------------------------------------------
# Rust

"cargo:sleek" = "latest"   # sql formatter
"cargo:scooter" = "latest" # find and replace mechanism

[settings]
idiomatic_version_file_enable_tools = ["python"]
experimental = true
lockfile = true

  [settings.npm]
  # use bun as the package manager for 'npm' register
  bun = true
