[tools]
# -------------------------------------------------------
# Environments

go = "latest"
node = "25"
bun = "latest"
rust = "latest"

# -------------------------------------------------------
# npm

"npm:prettier" = "latest"
"npm:eslint" = "latest"
"npm:typescript" = "latest"
"npm:ts-node" = "latest"
"npm:pnpm" = "latest"
"npm:yarn" = "latest"

# -------------------------------------------------------
# Go

# Go Team Tools
"go:golang.org/x/perf/cmd/benchstat" = "latest"
"go:golang.org/x/tools/cmd/deadcode" = "latest"

# Go Tools
"github:abice/go-enum" = "latest"
"github:Zxilly/go-size-analyzer" = "latest"
"github:homeport/dyff" = "v1"               # yaml differ 
"github:caarlos0/svu" = "latest"
"github:amir20/dtop" = "v0.5.0"             # docker tui

# Personal Go Tools
"go:github.com/hay-kot/mmdot" = "v0.3.0"
"go:github.com/hay-kot/mdparse" = "v0.1.0"
"github:steveyegge/beads" = "v0.49"
"github:hay-kot/gofind" = "v0.4.1"
"github:hay-kot/scaffold" = "v0.12.1"
"github:hay-kot/hive" = "v0.29.0"
"github:zjrosen/perles" = "v0.7.83"

"forgejo:gitea/tea" = { version = "v0.11.1", api_url = "https://gitea.com/api/v1" }
# -------------------------------------------------------
# Rust

"github:sxyazi/yazi" = "v25.5.31"         # file explorer tui
"github:thomasschafer/scooter" = "latest" # find and replace mechanism
"cargo:sleek" = "latest"                  # sql formatter

[settings]
idiomatic_version_file_enable_tools = ["python"]
experimental = true
lockfile = true

  [settings.npm]
  # use bun as the package manager for 'npm' register
  bun = true
